FROM rust:1.68.2-alpine AS builder
WORKDIR /usr/src/leak_secret
COPY . .
RUN cargo install --path .

FROM alpine
# RUN apt-get update & apt-get install -y extra-runtime-dependencies & rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/leak_secret /usr/local/bin/leak_secret
CMD ["leak_secret"]